AWSTemplateFormatVersion: '2010-09-09'
Resources:
  InsecureLambda:
    Properties:
      Code:
        ZipFile: "def handler(event, context):\n    api_key = \"REPLACED_SECRET_KEY\"\
          \n    print(\"Insecure Function\")\n"
      FunctionName: InsecureFunction
      Handler: index.handler
      Role: arn:aws:iam::123456789012:role/lambda-role
      Runtime: python3.9
    Type: AWS::Lambda::Function
  PublicS3Bucket:
    Properties:
      AccessControl: Private
    Type: AWS::S3::Bucket
