AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket open to public, Lambda with secrets in plain text
Resources:
  InsecureLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: "def handler(event, context):\n    api_key = \"HARDCODED_SECRET_KEY\"\
          \n    print(\"Insecure Function\")\n"
      FunctionName: InsecureFunction
      Handler: index.handler
      Role: arn:aws:iam::123456789012:role/lambda-role
      Runtime: python3.9
  PublicS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketPolicy:
        Version: '2012-10-17'
        Statement:
        - Effect: Deny
          Principal: '*'
          Action: s3:*
          Resource:
            Fn::Sub: arn:aws:s3:::${PublicS3Bucket}/*
          Condition:
            Bool:
              aws:SecureTransport: 'false'
