AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket access, Lambda with environment variable

Resources:
  PublicS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead

  InsecureLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: InsecureFunction
      Handler: index.handler
      Role: arn:aws:iam::123456789012:role/lambda-role
      Code:
        ZipFile: |
          def handler(event, context):
              api_key = "HARDCODED_SECRET_KEY"
              print("Insecure Function")
      Runtime: python3.9