AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket access, Lambda with environment variable
Resources:
  InsecureLambda:
    Properties:
      Code:
        ZipFile: "def handler(event, context):\n    api_key = !Ref SecretKey\n   \
          \ print(\"Insecure Function\")\n"
      Environment:
        Variables:
          SecretKey:
            Ref: SecretKey
      FunctionName: InsecureFunction
      Handler: index.handler
      Role:
        Fn::GetAtt: LambdaRole.Arn
      Runtime: python3.9
    Type: AWS::Lambda::Function
  PublicS3Bucket:
    Properties:
      AccessControl: Private
    Type: AWS::S3::Bucket
  LambdaRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
        Version: '2012-10-17'
      Policies:
      - PolicyDocument:
          Statement:
          - Action: logs:CreateLogGroup
            Effect: Allow
            Resource: arn:aws:logs:*:*:*
          - Action: logs:CreateLogStream
            Effect: Allow
            Resource: arn:aws:logs:*:*:*/*
          - Action: logs:PutLogEvents
            Effect: Allow
            Resource: arn:aws:logs:*:*:*/*
          Version: '2012-10-17'
        PolicyName: LambdaLogsPolicy
    Type: AWS::IAM::Role
