AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket access, Lambda with environment variable
Resources:
  InsecureLambda:
    Properties:
      Code:
        ZipFile: "def handler(event, context):\n    api_key = !Ref SecretKey\n   \
          \ print(\"Insecure Function\")\n"
      Environment:
        Variables:
          SecretKey:
            Ref: SecretKey
      FunctionName: InsecureFunction
      Handler: index.handler
      Role:
        Fn::GetAtt: LambdaRole.Arn
      Runtime: python3.9
    Type: AWS::Lambda::Function
  PublicS3Bucket:
    Properties:
      AccessControl: AuthenticatedRead
    Type: AWS::S3::Bucket
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: LambdaPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - s3:GetObject
            - s3:PutObject
            Resource:
              Fn::Sub: arn:aws:s3:::${PublicS3Bucket}/*
