AWSTemplateFormatVersion: '2010-09-09'
Description: secure VPC with security groups
Resources:
  SecureSubnet:
    Properties:
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      VpcId:
        Ref: secureVPC
    Type: AWS::EC2::Subnet
  SecureVPC:
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
      - Key: Name
        Value: secureVPC
    Type: AWS::EC2::VPC
  SecurityGroup:
    Properties:
      GroupDescription: Allow necessary traffic only
      SecurityGroupIngress:
      - CidrIp: YOUR_IP_RANGE
        FromPort: YOUR_FROM_PORT
        IpProtocol: tcp
        ToPort: YOUR_TO_PORT
      VpcId:
        Ref: secureVPC
    Type: AWS::EC2::SecurityGroup
