AWSTemplateFormatVersion: '2010-09-09'
Description: Insecure VPC with open security groups

Resources:
  InsecureVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: InsecureVPC

  InsecureSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref InsecureVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true

  OpenSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow all traffic
      VpcId: !Ref InsecureVPC
      SecurityGroupIngress:
        - IpProtocol: "-1"
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0