AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket open to public, Lambda with secrets in plain text
Resources:
  InsecureLambda:
    Properties:
      Code:
        ZipFile: "def handler(event, context):\n    api_key = !Ref SecretKey\n   \
          \ print(\"Insecure Function\")\n"
      FunctionName: InsecureFunction
      Handler: index.handler
      Role: arn:aws:iam::123456789012:role/lambda-role
      Runtime: python3.9
    Type: AWS::Lambda::Function
    Metadata:
      AWS::CloudFormation::Init:
        config:
          files:
            /tmp/secret.txt:
              content:
                Fn::Sub: 'api_key=${SecretKey}

                  '
  PublicS3Bucket:
    Properties:
      AccessControl: PublicRead
    Type: AWS::S3::Bucket
