AWSTemplateFormatVersion: '2010-09-09'
Description: Insecure VPC with open security groups
Resources:
  InsecureSubnet:
    Properties:
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: false
      VpcId:
        Ref: InsecureVPC
    Type: AWS::EC2::Subnet
  InsecureVPC:
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
      - Key: Name
        Value: InsecureVPC
    Type: AWS::EC2::VPC
  OpenSecurityGroup:
    Properties:
      GroupDescription: Allow necessary traffic only
      SecurityGroupIngress:
      - CidrIp: 10.0.0.0/16
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      VpcId:
        Ref: InsecureVPC
    Type: AWS::EC2::SecurityGroup
