AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 with IAM role and encrypted EBS
Resources:
  AdminRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
        Version: '2012-10-17'
      Policies:
      - PolicyDocument:
          Statement:
          - Action: sts:*
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: AccessPolicy
      RoleName: AdminRole
    Type: AWS::IAM::Role
  EC2:
    Properties:
      BlockDeviceMappings:
      - DeviceName: /dev/xvda
        Ebs:
          Encrypted: true
          VolumeSize: 20
      IamInstanceProfile:
        Ref: AdminRole
      ImageId: ami-0c55b159cbfafe1f0
      InstanceType: t2.micro
      KeyName: secure-key
    Type: AWS::EC2::Instance
