AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 with wildcard IAM role and unencrypted EBS

Resources:
  AdminRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: WildcardAdminRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: FullAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"

  VulnerableEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c55b159cbfafe1f0
      InstanceType: t2.micro
      KeyName: insecure-key
      IamInstanceProfile: !Ref AdminRole
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 20
            Encrypted: false